# Generated by Django 5.2.1 on 2025-05-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ful_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ful_name_en',
            new_name='full_name_en',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ful_name_ru',
            new_name='full_name_ru',
        ),
    ]
